name = "loverlay"
compatibility_date = "2024-09-19"
pages_build_output_dir = "dist"

[vars]
NODE_ENV = "production"
ADMIN_EMAIL = "pavel@pokataev.com"

[[d1_databases]]
binding = "DB"
database_id = "ce057c27-eccb-498f-bd4a-5cc82d80da9f"
database_name = "loverlay"

# Environment variables for the build
[env.production.vars]
NODE_ENV = "production"
ADMIN_EMAIL = "pavel@pokataev.com"

[[env.production.d1_databases]]
binding = "DB"
database_id = "ce057c27-eccb-498f-bd4a-5cc82d80da9f"
database_name = "loverlay"

[[r2_buckets]]
binding = "R2"
bucket_name = "loverlay"

[[env.production.r2_buckets]]
binding = "R2"
bucket_name = "loverlay"
